### ISSUE TITLE
Kontaktinformasjon: Epostlenker mangler protokoll 

### ISSUE THREAD

**Issue by bjornreppen** [kartverket/Geonorge.Kartkatalog.React#4]
Fra: https://kartkatalog.geonorge.no/metadata/5857ec0a-8d2c-4cd8-baa2-0dc54ae213b4

![image](https://user-images.githubusercontent.com/281359/66204560-63393380-e6ab-11e9-9a3a-f5f52743031a.png)

Istedet for at klikk på epostlenker åpner favorittmailleser havner man istedet på en tom webside, eks. https://kartkatalog.geonorge.no/metadata/wms@miljodir.no

**Comment by dagolav** [comment]
Takk, det er rettet og kommer med i neste release.
